[project]
name = "tcr-registry"
clarity_version = "2.1.0"
description = "Token Curated Registry (TCR) with Voting"

[contracts.tcr]
path = "contracts/tcr.clar"

[contracts.voting]
path = "contracts/voting.clar"

[repl.analysis]
passes = ["check_checker"]
